name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: -vv --latest
        env:
          OUTPUT: CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
